// Sources stay in the root. Directory copies also work in VS Code Live Server.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { localizeHTML } from './localize-html.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const routes = JSON.parse(fs.readFileSync(path.join(root, 'routes.json'), 'utf8'));
const englishRoutes = JSON.parse(fs.readFileSync(path.join(root, 'routes-en.json'), 'utf8'));
if (Object.keys(routes).sort().join() !== Object.keys(englishRoutes).sort().join()) throw new Error('Every page needs an English route');
const redirects = [{ source: '/', destination: '/anasayfa', permanent: true }, { source: '/en', destination: englishRoutes['index.html'], permanent: true }];
const rewrites = [];
const sitemap = [];
const pairs = Object.fromEntries(Object.entries(routes).map(([file, tr]) => [file, { tr, en: englishRoutes[file] }]));
fs.writeFileSync(path.join(root, 'route-map.js'), '// Generated by npm run build.\nwindow.ARKESOFT_ROUTES = ' + JSON.stringify(pairs) + ';\n');
for (const [file, route] of Object.entries(routes)) {
  const sourcePath = path.join(root, file);
  let html = fs.readFileSync(sourcePath, 'utf8');
  const canonical = html.match(/rel="canonical" href="([^"]+)"/)[1];
  const origin = new URL(canonical).origin;
  const enURL = origin + englishRoutes[file];
  html = html.replace(/<link rel="alternate" hreflang="[^"]+"[^>]*>\n?/g, '');
  html = html.replace(/(<link rel="canonical"[^>]*>)/, `$1\n<link rel="alternate" hreflang="tr" href="${canonical}">\n<link rel="alternate" hreflang="en" href="${enURL}">`);
  if (!html.includes('src="/route-map.js"')) html = html.replace('<script src="/preferences.js">', '<script src="/route-map.js"></script>\n<script src="/preferences.js">');
  html = html.replace(/\n<a class="wa-support"[\s\S]*?<\/a>\n(?=<\/body>)/g, '\n');
  fs.writeFileSync(sourcePath, html);
  const directory = path.join(root, route);
  fs.mkdirSync(directory, { recursive: true });
  fs.writeFileSync(path.join(directory, 'index.html'), html);
  const englishDirectory = path.join(root, englishRoutes[file]);
  fs.mkdirSync(englishDirectory, { recursive: true });
  fs.writeFileSync(path.join(englishDirectory, 'index.html'), localizeHTML(html, routes, englishRoutes));
  redirects.push({ source: englishRoutes[file] + '/index.html', destination: englishRoutes[file], permanent: true });
  rewrites.push({ source: englishRoutes[file], destination: englishRoutes[file] + '/index.html' });
  sitemap.push(canonical, enURL);
  for (const source of [`/${file}`, `${route}/index.html`]) {
    redirects.push({ source, destination: route, permanent: true });
  }
  const alias = '/' + file.replace(/\.html$/, '');
  if (alias !== route) redirects.push({ source: alias, destination: route, permanent: true });
  rewrites.push({ source: route, destination: `/${file}` });
}
const notFoundPath = path.join(root, '404.html');
let notFound = fs.readFileSync(notFoundPath, 'utf8');
if (!notFound.includes('src="/route-map.js"')) fs.writeFileSync(notFoundPath, notFound.replace('<script src="/preferences.js">', '<script src="/route-map.js"></script>\n<script src="/preferences.js">'));
fs.writeFileSync(path.join(root, 'sitemap.xml'), '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + sitemap.map(url => `<url><loc>${url}</loc></url>`).join('\n') + '\n</urlset>\n');
const vercelPath = path.join(root, 'vercel.json');
const vercel = JSON.parse(fs.readFileSync(vercelPath, 'utf8'));
Object.assign(vercel, { trailingSlash: false, redirects, rewrites });
fs.writeFileSync(vercelPath, JSON.stringify(vercel, null, 2) + '\n');
// Explicit 200 rewrites take precedence over Pages' automatic HTML redirects.
fs.writeFileSync(path.join(root, '_redirects'), '# Generated by npm run build\n' +
  redirects.map(({source, destination}) => `${source} ${destination} 301`).join('\n') + '\n' +
  rewrites.map(({source}) => `${source}/ ${source} 301`).join('\n') + '\n' +
  rewrites.map(({source, destination}) => `${source} ${destination} 200`).join('\n') + '\n');
const apache = [
  '# Generated by npm run build; Apache 2.4 with mod_rewrite.',
  'Options -Indexes -MultiViews', 'DirectorySlash Off', 'RewriteEngine On',
  'ErrorDocument 404 /404.html',
];
for (const { source, destination } of redirects) {
  const escaped = source.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  apache.push(`RewriteCond %{THE_REQUEST} "\\s${escaped}(?:[?\\s])"`,
    `RewriteRule ^${escaped.slice(1)}$ ${destination} [R=301,L,NE]`);
}
for (const { source: route, destination } of rewrites) {
  apache.push(`RewriteRule ^${route.slice(1)}/$ ${route} [R=301,L,NE]`,
    `RewriteRule ^${route.slice(1)}$ ${destination.slice(1)} [END]`);
}
fs.writeFileSync(path.join(root, '.htaccess'), apache.join('\n') + '\n');
console.log(`Built ${rewrites.length} Turkish/English routes, localized pages and hosting redirects.`);
